BlogForDevelopers.WebMvc3/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogForDevelopers.WebMvc3.Areas.Admin.Controllers
{
	[Authorize]
    public class HomeController : Controller
    {
        //
        // GET: /Admin/Home/
		[HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("index", "post");
        }

    }
}

BlogForDevelopers.WebMvc3/Controllers/HomeController.cs
using BlogForDevelopers.Domain.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogForDevelopers.WebMvc3.Controllers
{
    public class HomeController : Controller
    {
		//
        // GET: /Home/
		[HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

BlogForDevelopers.WebMvc3/Controllers/PostController.cs
using BlogForDevelopers.Domain.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogForDevelopers.WebMvc3.Controllers
{
	public class PostController : Controller
	{
		private PostService postService;

		public PostController(PostService postService)
		{
			this.postService = postService;
		}

		[HttpGet]
		public ActionResult Index(int day, int month, int year, string title)
		{
			DateTime datePublished = new DateTime(year, month, day);

			return View(this.postService.GetPublished(datePublished, title));
		}

		[HttpGet]
		public ActionResult Posts()
		{
			return View(this.postService.GetAllPublished());
		}

		[HttpGet]
		[ChildActionOnly]
		public PartialViewResult LastPost()
		{
			return PartialView("_LastPost", this.postService.GetLastTop(8));
		}
	}
}

BlogForDevelopers.WebMvc3/Controllers/TagController.cs
using BlogForDevelopers.Domain.ObjectValue;
using BlogForDevelopers.Domain.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace BlogForDevelopers.WebMvc3.Controllers
{
    public class TagController : Controller
    {
		private TagService tagService;
		private PostService postService;

		public TagController(TagService tagService, PostService postService)
		{
			this.tagService = tagService;
			this.postService = postService;
		}
		
        // GET: /Tags/
        public ActionResult Index(string name)
        {
			Tag tag = new Tag() { 
				Name = name
			};

            return View(this.postService.GetAllByTag(tag));
        }

		[HttpGet]
		[ChildActionOnly]
		public PartialViewResult TagsCloud()
		{
			return PartialView("_TagsCloud", this.tagService.GetTagsNameCount());
		}
	
    }
}

BlogForDevelopers.WebMvc3/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Index";
	ViewBag.Background = "#cccccc";
	ViewBag.MetroScroll = "metro-scroll";
	ViewBag.ShowMessageFooter = true;
}
<div class="metro-sections">

	@{Html.RenderAction("LastPost", "Post");}

	<div class="metro-section size2">
		<a href="/about" class="tile @BlogForDevelopers.WebMvc3.App_Code.ClassCssBackgroundColor.Green">
			<div class="tile-icon-large">
				<h2 style="margin-top: 35px; color: #fff;">{ Sobre }</h2>
			</div>
		</a>

		<a href="/contact" class="tile @BlogForDevelopers.WebMvc3.App_Code.ClassCssBackgroundColor.Orange">
			<div class="tile-icon-large">
				<img src="@Url.Content("~/Content/img/mail-128.png")">
			</div>
			<div class="tile-label">Contato</div>
		</a>


		<a href="/projetos" class="tile tile-double @BlogForDevelopers.WebMvc3.App_Code.ClassCssBackgroundColor.Red">
			<div class="tile-icon-large">
				<h3 style="margin-top: 35px; color: #fff;">{ Projetos }</h3>
			</div>
		</a>
	</div>

	@{Html.RenderAction("TagsCloud", "Tag");}
</div>

BlogForDevelopers.WebMvc3/Views/Home/_LastPost.cshtml
@model IList<BlogForDevelopers.Domain.Entities.Post>
@using BlogForDevelopers.Web.App_Code

@{
	ViewBag.Title = "Index";
	ViewBag.Background = "#cccccc";
	ViewBag.MetroScroll = "metro-scroll";
}

<div class="metro-section size4" id="section-general">
	@{
		string titleClassCss = string.Empty;

		for (int i = 0; i < Model.Count; i++)
		{
			if (i == 0)
			{
				titleClassCss = string.Concat("tile tile-double tile-double-vertical ", BlogForDevelopers.Web.App_Code.ClassCssBackgroundColor.Blue);
			}
			else
			{
				titleClassCss = string.Concat("tile ", ClassCssBackgroundColor.BackgroundColors[i]);
			}
		
		<a href="/post/@Model[i].DatePublished.ToString("dd/MM/yyyy")/@Model[i].TitleUrl" class="@titleClassCss">
			<div class="tile-announce">
				<div class="announce-content">
					@Html.Raw(ImageInContent.GetFristImage(Model[i].Content))
				</div>
				<div class="announce-description">
					<div class="label @ClassCssLabelColors.LabelColors[i]">@Model[i].DatePublished.ToString("dd/MM/yyyy")<b class="stick"></b></div>

					<div class="text" style="font-size: 0.9em">@Model[i].Title</div>
				</div>
			</div>
		</a>
		}

		if (Model.Count >= 8)
		{
			<a class="tile @ClassCssBackgroundColor.OrangeDark" href="/posts">
				<div class="tile-icon-large">
					<h2 style="margin-top: 35px; color: #fff;">{ Todos }</h2>
				</div>
			</a>
		}
	}
</div>